---
- name: common | Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
  become: yes

- name: common | Install software-properties-common
  apt:
    name: software-properties-common
    state: present
  become: yes

- name: common | Install build-essentials
  apt:
    name: build-essential
    state: present
  become: yes

- name: common | Install additional packages
  apt:
    name: "{{ common__packages }}"
    state: present
  become: yes
