---
# tasks file for ansible-unattended-upgrades
- name: unattended-upgrades | Copy 10periodic configuration file
  template:
    src: "etc/apt/apt.conf.d/10periodic.j2"
    dest: "/etc/apt/apt.conf.d/10periodic"
    owner: "root"
    group: "root"
    mode: "0644"
  become: yes

- name: unattended-upgrades | Copy 50unattended-upgrades configuration file
  template:
    src: "etc/apt/apt.conf.d/50unattended-upgrades.j2"
    dest: "/etc/apt/apt.conf.d/50unattended-upgrades"
    owner: "root"
    group: "root"
    mode: "0644"
  become: yes
