---
# tasks file for ansible-nodejs

- name: nodejs - check requested version number
  fail:
    msg: "NodeJS version {{ nodejs__version }} is not supported."
  when: nodejs__version != '6.x' and nodejs__version != '7.x' and nodejs__version != '8.x' and nodejs__version != '10.x' and nodejs__version != '12.x' and nodejs__version != '14.x'

- name: nodejs - add NodeSource apt key
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
  become: yes

- name: nodejs - add NodeSource repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_{{ nodejs__version }} {{ ansible_distribution_release }} main
    state: present
    filename: 'nodesource'
  become: yes

- name: nodejs - add NodeSource src repository
  apt_repository:
    repo: deb-src https://deb.nodesource.com/node_{{ nodejs__version }} {{ ansible_distribution_release }} main
    state: present
    filename: 'nodesource'
  become: yes

- name: nodejs - install nodejs
  apt:
    name: nodejs
    state: "{{ nodejs__install_state }}"
    update-cache: yes
  become: yes
