---
# tasks file for ansible-ssh

- name: ssh - ensure ssh server is installed
  apt: name=openssh-server state=present
  become: yes

- name: ssh - ensure ssh server is started
  service: name=sshd state=started
  become: yes

- name: ssh - ensure ssh server is enabled
  service: name=sshd enabled=yes
  become: yes

- name: ssh - set up sftponly
  include_tasks: sftponly.yml
  when: ssh__sftponly is defined

- name: ssh - copy and validate sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 644
    validate: '/usr/sbin/sshd -t -f %s'
  become: yes
  notify: ssh - restart sshd

- name: ssh - install authorized keys
  authorized_key:
    user: "{{ item.user | default(ssh__authorized_keys_default_user) }}"
    state: "{{ item.state | default('present') }}"
    key: "{{ item.key }}"
  with_items: "{{ ssh__authorized_keys }}"
  when: ssh__authorized_keys is defined
  tags:
    - authorized_keys
